"use client";

import { useState } from "react";

export default function ServicesInteractive() {

  const [active, setActive] = useState(0);

 const services = [
  {
    title: "AI Diet Assistant",
    description: "Get personalized meal plans generated by AI based on your health goals.",
    image: "/ai.jpg"
  },
  {
    title: "Dietician Consultation",
    description: "Connect with certified nutrition experts for professional guidance.",
    image: "/dietician.jpg"
  },
  {
    title: "Dietary Kitchen",
    description: "Order healthy meals prepared by our dietary kitchen.",
    image: "/kitchen.jpg"
  },
  {
    title: "Meal Tracking",
    description: "Track your meals and progress easily.",
    image: "/meal.jpg"
  },
  {
    title: "Smart Reminders",
    description: "Never miss your healthy routine.",
    image: "/track.jpg"
  }
];

  return (
    <section className="services-section">

      <h2 className="services-title">
        How SmartDiet Hub Helps You
      </h2>

      <div className="services-container">

        {/* LEFT TEXT */}

        <div className="services-list">

          {services.map((service, index) => (

            <div
              key={index}
              className={`service-item ${
                active === index ? "active" : ""
              }`}
              onMouseEnter={() => setActive(index)}
            >

              <h3>{service.title}</h3>

              <p>{service.description}</p>

            </div>

          ))}

        </div>

        {/* RIGHT IMAGE */}

        <div className="services-image">

          <img
            src={services[active].image}
            alt={services[active].title}
          />

        </div>

      </div>

    </section>
  );
}